### ISSUE TITLE
Compiling with custom build riscv tools (gcc/binutils)

### ISSUE THREAD

**Issue by MarcKarasek** [diodesign/diosix#18]
What do you need to do to use a custom built tools for compiling?

In the other issue you said to change the ld/ar  
To override the linker paths, you need to edit the .cargo/config files in src/hypervisor and src/services and change the appropriate settings

Are there other settings to change the other tools?

Currently it fails:
Compiling diosix-services v1.0.0 (/media/marckarasek/source/diosix/src/services)
error: failed to run custom build command for `diosix-services v1.0.0 (/media/marckarasek/source/diosix/src/services)`

Caused by:
  process didn't exit successfully: `/media/marckarasek/source/diosix/src/services/target/debug/build/diosix-services-f5f431a80a102f38/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to execute command to assemble src/supervisor-riscv/asm/entry.s: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ../mason/build.rs:323:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::expect
               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/result.rs:997:23
     4: build_script_build::assemble
               at ./../mason/build.rs:310:18
     5: build_script_build::assemble_directory
               at ./../mason/build.rs:281:21
     6: build_script_build::main
               at ./../mason/build.rs:176:9
     7: core::ops::function::FnOnce::call_once
               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: Recipe `_services` failed on line 204 with exit code 101

**Comment by MarcKarasek** [comment]
I tried your ripmason branch and it does compile but fails on running qemu ..  

qemu-system-riscv64: GLib: g_mapped_file_unref: assertion 'file != NULL' failed

Looks like the file diosix is just 616 bytes long?

**Comment by MarcKarasek** [comment]
FYI: Version of tools I have compiled
riscv64-unknown-linux-gnu-gcc (GCC) 9.2.0
GNU objcopy (GNU Binutils) 2.32

**Comment by diodesign** [comment]
Hi -- thanks. There is something strange going on with `binutils`, which may be my fault.

On a Debian testing/bullseye system with `riscv64-linux-gnu-ld` version `2.35.2`, using the latest development branch (`ripmason`, commit diodesign/diosix@6b66e185a1e16fd35b80f9620255c62dd175046a), I get an assertion failure:

```
  = note: riscv64-linux-gnu-ld: BFD (GNU Binutils for Debian) 2.35.2 assertion fail elfnn-riscv.c:1765
          riscv64-linux-gnu-ld: BFD (GNU Binutils for Debian) 2.35.2 assertion fail elfnn-riscv.c:1798
```

On a Fedora 32 system with `riscv64-linux-gnu-ld` version `2.34-2.fc32`, I get a completed, running build of Diosix. I recommend `binutils` version `2.34` as that seems to work at least. If you get a small Diosix executable then it's likely that an empty ELF file has been generated due to an unreported failure in the build process.

Please try the latest `ripmason` branch -- `git pull` it, `just clean` and then `just` to build and run it in Qemu, and see if that works for you. I'm working on a way to either build a minimal known-good `binutils` in the Diosix build tree, figure out what I'm doing that's upsetting `binutils` version `2.35.x`, or write my own minimal linker...

**Comment by diodesign** [comment]
I'm going to suggest moving this into one issue #17 to get the bottom of the `binutils` problem -- thanks
